### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by jenna-h**

### CODE REVIEW

**Review by jorlows — COMMENTED** [review]
Only quick Q is looks like there is still a /* TODO(jenna): WHY ARE THESE IN THE HEADER FILE */

**Comment by jenna-h** [comment]
Good point XD

Basically, that CSS keeps track of all of the alert boxes (and alert-box-like things) that appear in the app. Notably, the popups that appear when you try to add new puzzles.

I think it might also affect the login page? Not sure.

Anyway, there's a broader issue here of none of the code being in sensible places and I don't really want to take it on right now—

We can file an issue for more serious refactoring and handle it some other time.

**Review by jorlows — APPROVED** [review]
Sounds good, lets do it then

**Comment by jenna-h** [comment]
As mentioned above, filed https://github.com/simhunt/wow/issues/31

**Pull request merged**
