### PR TITLE
take two of gravitar removal

### PR DESCRIPTION
**Pull request by jorlows**
now maybe without package changes

### CODE REVIEW

**Review by allenpark — APPROVED** [review]

**Comment by jenna-h** [comment]
LGTM, but the front page (before you log in) still shows the gravatar as you type and asks for an email address ("optional; used to look up [linked]Gravatar"). This is just weird if we're not using gravatar any more. Furthermore, the dropdown with your chosen username at the top right still displays your gravatar, and I think its presence is confusing if the gravatar is not being used anywhere else. 

Do you intend to eliminate these references as well?

**Comment by jorlows** [comment]
Oh these are great callouts. Will work on them before merging.

**Comment by jorlows** [comment]
woops accidentally closed

**Comment by jenna-h** [comment]
LGTM. Thanks!

**Pull request merged**
